### ISSUE TITLE
Images?

### ISSUE THREAD

**Issue by candidia** [BesrourMS/Airlines#1]
Love the library. Wondering if we could get some kind of field added for logos. I think a schema like the following would be perfect!

![image](https://user-images.githubusercontent.com/9855031/80060493-90ccb980-84e3-11ea-8bfc-a27f0d196986.png)

**Comment by BesrourMS** [comment]
@CSFlorin is_lowcost is now available :)

**Comment by BesrourMS** [comment]
@CSFlorin logo is now available, I find a cdn for logos while updating the library today 😄
